//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.22 at 11:56:27 AM EDT 
//


package com.smkw.commerce.inventory.xml;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

import javax.persistence.Embeddable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ItemMovement" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="StoreId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="ItemNum" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="PackNum" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="QtySold" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                   &lt;element name="NetSales" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                   &lt;element name="RtnToInv" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                   &lt;element name="RtnDamaged" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                   &lt;element name="DiscAmt" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                   &lt;element name="MarkdownAmt" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                   &lt;element name="CouponAmt" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "itemMovement"
})
@XmlRootElement(name = "IMMessage")
public class IMMessage {

    @XmlElement(name = "ItemMovement")
    protected List<IMMessage.ItemMovement> itemMovement;

    /**
     * Gets the value of the itemMovement property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the itemMovement property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getItemMovement().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link IMMessage.ItemMovement }
     * 
     * 
     */
    public List<IMMessage.ItemMovement> getItemMovement() {
        if (itemMovement == null) {
            itemMovement = new ArrayList<IMMessage.ItemMovement>();
        }
        return this.itemMovement;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="StoreId" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="ItemNum" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="PackNum" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="QtySold" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *         &lt;element name="NetSales" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *         &lt;element name="RtnToInv" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *         &lt;element name="RtnDamaged" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *         &lt;element name="DiscAmt" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *         &lt;element name="MarkdownAmt" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *         &lt;element name="CouponAmt" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "storeId",
        "itemNum",
        "packNum",
        "qtySold",
        "netSales",
        "rtnToInv",
        "rtnDamaged",
        "discAmt",
        "markdownAmt",
        "couponAmt"
    })
    @Embeddable
    public static class ItemMovement {

        @XmlElement(name = "StoreId", required = true)
        protected String storeId;
        @XmlElement(name = "ItemNum", required = true)
        protected String itemNum;
        @XmlElement(name = "PackNum")
        protected int packNum;
        @XmlElement(name = "QtySold", required = true)
        protected BigDecimal qtySold;
        @XmlElement(name = "NetSales", required = true)
        protected BigDecimal netSales;
        @XmlElement(name = "RtnToInv", required = true, nillable = true)
        protected BigDecimal rtnToInv;
        @XmlElement(name = "RtnDamaged", required = true, nillable = true)
        protected BigDecimal rtnDamaged;
        @XmlElement(name = "DiscAmt", required = true, nillable = true)
        protected BigDecimal discAmt;
        @XmlElement(name = "MarkdownAmt", required = true, nillable = true)
        protected BigDecimal markdownAmt;
        @XmlElement(name = "CouponAmt", required = true, nillable = true)
        protected BigDecimal couponAmt;

        /**
         * Gets the value of the storeId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getStoreId() {
            return storeId;
        }

        /**
         * Sets the value of the storeId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setStoreId(String value) {
            this.storeId = value;
        }

        /**
         * Gets the value of the itemNum property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getItemNum() {
            return itemNum;
        }

        /**
         * Sets the value of the itemNum property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setItemNum(String value) {
            this.itemNum = value;
        }

        /**
         * Gets the value of the packNum property.
         * 
         */
        public int getPackNum() {
            return packNum;
        }

        /**
         * Sets the value of the packNum property.
         * 
         */
        public void setPackNum(int value) {
            this.packNum = value;
        }

        /**
         * Gets the value of the qtySold property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getQtySold() {
            return qtySold;
        }

        /**
         * Sets the value of the qtySold property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setQtySold(BigDecimal value) {
            this.qtySold = value;
        }

        /**
         * Gets the value of the netSales property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getNetSales() {
            return netSales;
        }

        /**
         * Sets the value of the netSales property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setNetSales(BigDecimal value) {
            this.netSales = value;
        }

        /**
         * Gets the value of the rtnToInv property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getRtnToInv() {
            return rtnToInv;
        }

        /**
         * Sets the value of the rtnToInv property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setRtnToInv(BigDecimal value) {
            this.rtnToInv = value;
        }

        /**
         * Gets the value of the rtnDamaged property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getRtnDamaged() {
            return rtnDamaged;
        }

        /**
         * Sets the value of the rtnDamaged property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setRtnDamaged(BigDecimal value) {
            this.rtnDamaged = value;
        }

        /**
         * Gets the value of the discAmt property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getDiscAmt() {
            return discAmt;
        }

        /**
         * Sets the value of the discAmt property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setDiscAmt(BigDecimal value) {
            this.discAmt = value;
        }

        /**
         * Gets the value of the markdownAmt property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getMarkdownAmt() {
            return markdownAmt;
        }

        /**
         * Sets the value of the markdownAmt property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setMarkdownAmt(BigDecimal value) {
            this.markdownAmt = value;
        }

        /**
         * Gets the value of the couponAmt property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getCouponAmt() {
            return couponAmt;
        }

        /**
         * Sets the value of the couponAmt property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setCouponAmt(BigDecimal value) {
            this.couponAmt = value;
        }

    }

}
